import clsx from "clsx";
import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
} from "next";
import Head from "next/head";
import { Rubik } from "next/font/google";
import { useRouter } from "next/router";
import { useCallback } from "react";

export const getServerSideProps = (ctx: GetServerSidePropsContext) => {
  console.log("cookie-headers", ctx.req.headers.cookie);
  return {
    props: {
      cookie: ctx.req.headers.cookie ?? null,
      host: ctx.req.headers.host,
    },
  };
};

const font = Rubik({
  subsets: ["latin-ext"],
});

export default function Banking(
  props: InferGetServerSidePropsType<typeof getServerSideProps>,
) {
  const triggerHello = useCallback(async () => {
    const resp = await fetch("/banking/api/hello", {
      method: "POST",
    });
    const json = (await resp.json()) as { message: string };
  }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx("z-20 flex min-h-screen flex-col", font.className)}>
        <nav className="bg-purple-100 px-20 py-4">
          <h2 className="text-xl font-semibold">
            Child App{" "}
            {props.host ? (
              <div className="inline">
                {" "}
                - Hosted on{" "}
                <span className="inline-block rounded bg-gray-300 px-2 py-0.5 font-mono text-gray-700">
                  {props.host}
                </span>
              </div>
            ) : (
              ""
            )}
          </h2>
        </nav>
        {props.cookie && (
          <div className="grow bg-rose-100 px-20 py-4">{`cookie -> ${props.cookie}`}</div>
        )}
        <div className="flex items-center gap-8 bg-rose-100 px-20 py-4">
          <button
            onClick={() => {
              triggerHello().then(() => console.log("triggered"));
            }}
            className="rounded bg-purple-500 px-2 py-1 text-white hover:bg-purple-700"
          >
            Trigger API from iframe
          </button>
          <div>
            Request should have cookie header as calls are going to
            <span className="inline-block rounded bg-gray-600 px-2 py-0.5 font-mono text-white">
              /banking/api/*
            </span>
          </div>
        </div>
      </main>
    </>
  );
}
